<?php
define('DB_SERVER', defined('_C5VT_DB_SERVER_C5') ? _C5VT_DB_SERVER_C5 : _C5VT_DB_SERVER);
define('DB_USERNAME', defined('_C5VT_DB_USERNAME_C5') ? _C5VT_DB_USERNAME_C5 : _C5VT_DB_USERNAME);
define('DB_PASSWORD', defined('_C5VT_DB_PASSWORD_C5') ? _C5VT_DB_PASSWORD_C5 : _C5VT_DB_PASSWORD);
define('DB_DATABASE', defined('_C5VT_DB_DATABASE_C5') ? _C5VT_DB_DATABASE_C5 : _C5VT_DB_DATABASE);

$_SERVER['REQUEST_URI'] = '/';
$_SERVER['HTTP_HOST'] = 'localhost';
define('BASE_URL', 'http://localhost');
